title    OmniOS
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-zen
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-zen.img
options  cow_spacesize=50% archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% systemd.firstboot=off quiet splash loglevel=3 rd.udev.log_level=3 vt.global_cursor_default=0 systemd.show_status=false rd.systemd.show_status=false
