title    OmniOS (console only, no launcher)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-zen
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-zen.img
options  cow_spacesize=2G archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% systemd.firstboot=off omnios.nolauncher
