title    OmniOS (console only, no launcher)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-zen
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-zen.img
options  archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% omnios.nolauncher
