title    Console only, for troubleshooting
sort-key 04
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-zen
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-zen.img
options  cow_spacesize=50% archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% systemd.firstboot=off omnios.nolauncher
